### ISSUE TITLE
Trigger unable to get subscriber uri across namespaces

### ISSUE THREAD

**Issue by erictg** [knative-sandbox/eventing-rabbitmq#1117]
**Describe the bug**
When a trigger/broker is in namespace A, it can not get the subscriber information for namespace B in order to forward events.

 **Expected behavior**
Trigger should be able to exist in namespace A and reference a service in namespace B

 **To Reproduce**
1) create namespaces "a" and "b"
2) create a broker in namespace "a"
3) create a service in namespace "b"
4) create a trigger in namespace "a" that references the broker in namespace a and references the subscriber in namespace "b"

 **Knative release version**
1.9.1

 **Additional context**
I already identified the location of the error. [Here](https://github.com/knative-sandbox/eventing-rabbitmq/blob/release-1.9/pkg/reconciler/trigger/trigger.go#L275) you will see that the subscriber ref namespace is overwritten to the namespace of the trigger without first checking if the namespace is empty. I am planning submit a pr to fix this myself, but wanted to document the issue for reference.

**Comment by gabo1208** [comment]
Awesome addition, thank you very much erictg :)! 💪🏼
