### ISSUE TITLE
rabbitmq-webhook-certs specified twice in release manifest

### ISSUE THREAD

**Issue by polivbr** [knative-sandbox/eventing-rabbitmq#1128]
**Describe the bug**

The released rabbitmq-source.yaml has the rabbitmq-webhook-certs Secret specified twice, which flux/kustomize chokes on.

 **Expected behavior**

The rabbitmq-webhook-certs is only  specified once.

 **Knative release version**

1.10.0

**Comment by gabo1208** [comment]
Nice discovery @polivbr !!! Sorry for the late response I'm a little occupied by my work :)

Here is the PR to fix it https://github.com/knative-sandbox/eventing-rabbitmq/pull/1173

Thank you very much for the report 💪🏼 !!
