### ISSUE TITLE
Random broker ingress behaviour when receiving binary format

### ISSUE THREAD

**Issue by lpfann** [knative-sandbox/eventing-rabbitmq#1152]
**Describe the bug**
When sending `binary` Cloudevents to a broker ingress I receive around 50% of time response code `400 Bad Request` and the ingress logs show:
```
"msg":"failed to extract event from request","commit":"d9f5856-dirty","error":"bad key, CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set"}
```
The other ~50% of times i get back `202` code without errors, **with an identical request**. So no changes to attributes or payload.

When using `structured` Cloudevents, i get back 100% `202` codes.

 **Expected behavior**
The behaviour should be deterministic. Either support binary content 100% of the time or fail 100% of the time.

 **To Reproduce**
Steps to reproduce the behavior.
Send event with binary format:
```bash
curl -v "http://broker-ingress" \
    -H "ce-id: bceeaa12-3637-4911-9315-7d70c2483b7f" \
    -H "ce-specversion: 0.3" \
    -H "ce-type: my-type" \
    -H "ce-source: curl" \
    -H "ce-content-type: application/json" \
    -H "ce-time: 2023-06-30T07:45:22.341714+00:00" \
    -d '{
    "message" : "Hello world!"
}'
```
and expect random error code behaviour.

Send event with structured format:
```bash
curl -v "http://broker-ingress" \
    -H "Content-Type: application/cloudevents+json" \
    -d '{
    "specversion" : "0.3",
    "type" : "my-type",
    "source" : "curl",
    "id" : "bceeaa12-3637-4911-9315-7d70c2483b7f",
    "time" : "2023-06-30T07:45:22.341714+00:00",
    "contenttype" : "application/json",
    "data" : {
        "message" : "Hello world!"
    }
}'
```
and expect 100% 202 code.

 **Knative release version**
1.10.0
 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by lpfann** [comment]
It seems to be caused by the content type header.
When changing `ce-content-type` to `ce-contenttype` it seems to be 100% `202` error code.

**Comment by gabo1208** [comment]
Just one thing the "Content-type" header is without the "ce-" prefix nor the "ce-contentype", the later is considered a CloudEvent extension.
The Content-type header is taken from the "datacontenttype" or "ce-datacontenttype"

But you are right that it should always produce the same error so I'll be checking out this.

**Comment by gabo1208** [comment]
Seems like you found a bug here: https://github.com/cloudevents/sdk-go/tree/main/v2/protocol/http It would be great for you to report it. I made a PR here to make the errors constant but nothing much to do in this project for that since your CloudEvent hits a corner case with their implementation using the wrong "ce-content-type" header.

Nice discovery and I encourage you to pursue the solution there :)! Thank you very much 💪🏼 !
