### ISSUE TITLE
RabbitMQ Trigger knativeerrordest extension

### ISSUE THREAD

**Issue by thomasjohansen** [knative-sandbox/eventing-rabbitmq#1154]
**Problem**
When a trigger fails and deadLetterSink is setup, It is not possible to see what Trigger (Service) failed on a specific event, because Extension in the Event is not set. 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Event consumer (developer)
System Integrator

**Exit Criteria**
When the failed event is recived by the deadLetterSink it must contain knativeerrordest in the Event Extension.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by gabo1208** [comment]
Related to [#833](https://github.com/knative-sandbox/eventing-rabbitmq/issues/833)
