### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by jonirap** [knative-sandbox/eventing-rabbitmq#1179]
When will the next version be relased?
Some bug fixes that have been merged are critical.
Thanks!

**Comment by gabo1208** [comment]
Next release is planned for the next knative version (in 2 weeks or so), but if you need any change I can schedule a patch release for Tuesdays any week

**Comment by jonirap** [comment]
That would be great!
I need [this merged PR](https://github.com/knative-sandbox/eventing-rabbitmq/pull/1147)

**Comment by gabo1208** [comment]
Ready! Created the cherry picks:
https://github.com/knative-sandbox/eventing-rabbitmq/pull/1180
https://github.com/knative-sandbox/eventing-rabbitmq/pull/1181
Next tuesday this will be in the 1.10.1 and 1.9.2 versions
