### ISSUE TITLE
Should use RabbitMQ policy instead of queue arguments

### ISSUE THREAD

**Issue by ChunyiLyu** [knative-sandbox/eventing-rabbitmq#264]
Hi 🙂 I’ve noticed that queues are configured with queue arguments, [like here](https://github.com/knative-sandbox/eventing-rabbitmq/blob/8778e9905cce25b8cd4bcaa8bc9004b1ab3f788a/pkg/reconciler/trigger/resources/queue.go#L73).

In general, we don’t recommend people to configure their queues with queue arguments. Instead, it’s a better practice to configure queues by using policies: https://www.rabbitmq.com/parameters.html#policies. If all your queues share the same configuration, you can have one policy that has the regex to match all queue names. That way you don’t need to set the same queue arguments for every single queue.

**Comment by xtreme-sameer-vohra** [comment]
Hey @benmoss 
Was this addressed as well since https://github.com/knative-sandbox/eventing-rabbitmq/issues/448 was closed ?

**Comment by benmoss** [comment]
Yep! closing
