### ISSUE TITLE
Update installation instructions to reflect the rabbitmqcluster as well messaging-topology-operator

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/eventing-rabbitmq#285]
Our install documents need to be updated.

**Comment by nickjameswebb** [comment]
@vaikas could you include some info on version compatibility with these changes? It's not very obvious that eventing-rabbitmq 0.22.0 isn't compatible with messaging-topo-operator latest, for example.

Thanks!

**Comment by vaikas** [comment]
Yeah, that's precisely what this issue is about.
