### ISSUE TITLE
Add validating webhook targeting our Broker class.

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/eventing-rabbitmq#304]
We should add a webhook that checks incoming Brokers and makes sure that if they have our BrokerClass, that we validate it, so we can move code like this out of the backend and instead fail fast.

https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/reconciler/broker/broker_config.go#L55
https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/reconciler/broker/broker_config.go#L75

**Comment by vaikas** [comment]
Well, we should still leave it in the backend in case somebody creates brokers without having installed the webhook, but still failing fast would be preferable.

**Comment by n3wscott** [comment]
+1 do it, sounds awesome.
