### ISSUE TITLE
nightly version for standalone broker returns 404

### ISSUE THREAD

**Issue by cheskayang** [knative-sandbox/eventing-rabbitmq#320]
Could not apply it following this url listed in doc
kubectl apply -f https://storage.googleapis.com/knative-nightly/eventing-rabbitmq/latest/rabbitmq-broker-standalone.yaml

however, this one works
kubectl apply -f https://storage.googleapis.com/knative-nightly/eventing-rabbitmq/latest/rabbitmq-standalone-broker.yaml

**Comment by vaikas** [comment]
Thanks and sorry about that :(

**Comment by cheskayang** [comment]
thx
