### ISSUE TITLE
dispatcher throws error on json.Unmarshal for legit cloud event

### ISSUE THREAD

**Issue by cheskayang** [knative-sandbox/eventing-rabbitmq#328]
I'm sending cloud events using https://github.com/cloudevents/sdk-javascript#readme.

when sending the event to rabbitmq broker, the dispatcher throws error 
```
failed to unmarshal event (NACK-ing and not re-queueing): json: cannot unmarshal object into Go value of type string
```
with the following message:
```
{
  "data": {
    "timeout": 2,
    "sent_at": 1622403421665
  },
  "datacontenttype": "application/json; charset=utf-8",
  "id": "cc99927b-2cb6-4171-8fca-6687579059f3",
  "source": "urn:event:from:my-api/resource/123",
  "specversion": "1.0",
  "time": "2021-05-30T19:37:01.666Z",
  "type": "your.event.source.type"
}
```

if I change datacontenttype from "application/json; charset=utf-8" to "application/json", the event can be handled properly. I'm bypassing this issue temporarily by overwriting this

you can reproduce by sending the above payload directly to a queue that is consumed by a dispatcher.

This seems to be an issue with the wabbit msg.Body() from https://github.com/knative-sandbox/eventing-rabbitmq/blob/c3aa10cc00b04df6744b45410d59f0cbf7acc1ec/pkg/dispatcher/dispatcher.go#L101

just using github.com/streadway/amqp and msg.Body was able to parse the json correctly

**Comment by vaikas** [comment]
Just making sure is this happening with the rabbitmq source, or when sending to the RabbitMQ Knative Broker?
Regardless, the dispatcher should be changed to handle this :)

**Comment by cheskayang** [comment]
@vaikas  thx for the quick response! It's happening with the broker. we are using the standalone broker.

**Comment by xtreme-sameer-vohra** [comment]
Can we reproduce this issue with Operator based Broker as well ?

**Comment by xtreme-sameer-vohra** [comment]
I was also unable to reproduce the problem with ([running latest](https://github.com/knative-sandbox/eventing-rabbitmq/commit/5cfcc6686cecca509e1a5bf3955c7ffce9b5f61a)) with the operator based broker.

Used the following curl command to the Broker, which was able to deliver the event to an event-display service without an error
```
curl localhost:8080 \
  -X POST \
  -H "Content-Type: application/cloudevents+json; charset=UTF-8" \
  -d '{
    "data": {
      "timeout": 2,
      "sent_at": 1622403421665
    },
    "datacontenttype": "application/json; charset=utf-8",
    "id": "cc99927b-2cb6-4171-8fca-6687579059f3",
    "source": "urn:event:from:my-api/resource/123",
    "specversion": "1.0",
    "time": "2021-05-30T19:37:01.666Z",
    "type": "your.event.source.type"
  }'
```

@cheskayang going to close the issue as we aren't able to reproduce the problem. Please feel free to open a new issue in case this still persists as a problem for you. Also please note https://github.com/knative-sandbox/eventing-rabbitmq/issues/411 🙇
