### ISSUE TITLE
Should use `rabbitmq/amqp091-go` instead of `streadway/amqp`

### ISSUE THREAD

**Issue by ChunyiLyu** [knative-sandbox/eventing-rabbitmq#366]
Library `github.com/streadway/amqp` (used in couple places in `pkg/reconciler/brokerstandalone/resources/`) hasn't been updated or maintained for a while. RabbitMQ team has hard forked the repo to https://github.com/rabbitmq/amqp091-go.

**Comment by xtreme-sameer-vohra** [comment]
Hey @ChunyiLyu 
Thanks for creating the issue. Based on the listed [Project Maturity](https://github.com/rabbitmq/amqp091-go#project-maturity), is there a milestone/planned release after which one could expect more stability in terms of breaking API changes ?

**Comment by gabo1208** [comment]
I managed to get this repo with the amqp091-go lib by just aliasing and changing the lib in the https://github.com/vaikas/wabbit repo, But im interested to see if we could add the wabbit lib or fork to the amqp091 project.

**Comment by xtreme-sameer-vohra** [comment]
Related #328

**Comment by xtreme-sameer-vohra** [comment]
> Hey @ChunyiLyu
> Thanks for creating the issue. Based on the listed [Project Maturity](https://github.com/rabbitmq/amqp091-go#project-maturity), is there a milestone/planned release after which one could expect more stability in terms of breaking API changes ?

cc @ikvmw @gvmw do either of y'all have context regarding at which point switching is a good idea ?

**Comment by gvmw** [comment]
Switching now is a good idea. This has been a long-time coming, and we would like to see as many users of the Go RabbitMQ client switch to a version which is officially supported and maintained.

cc @michaelklishin @GSantomaggio

**Comment by Gsantomaggio** [comment]
Totally agree.

Even not related I was thinking to propose the same change in [argo-events](https://github.com/argoproj/argo-events/blob/master/go.mod#L72)

**Comment by gabo1208** [comment]
Fixed on [this](https://github.com/knative-sandbox/eventing-rabbitmq/pull/436/files) PR and also upstreamed wabbit from a private fork we had :)
