### ISSUE TITLE
Write an spec for the comunication between amqp091 and cloudevents

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#388]
**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Producers, consumers and integrators

**Exit Criteria**
When you consume a message from a rabbitmq producer and want to transform it into a cloudevent and forward it to a consumer, it should be a clear behaviour definition to follow for the implementation

**Additional context (optional)**
See the  [cloudevents golang sdk](https://cloudevents.github.io/sdk-go/) and the protocol definitions

**Comment by gerhard** [comment]
https://hackmd.io/VUONMvUkRH2103cbJFetdg

**Comment by gabo1208** [comment]
Now moved to this repo, waiting for the next steps
