### ISSUE TITLE
Be smarter about retries

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/eventing-rabbitmq#409]
The dispatcher currently considers all !2xx || !3xx status codes as retryable, which is somewhat against the HTTP protocol spec:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/928976461374266e0c029bc61719c68b3dffad8b/pkg/dispatcher/dispatcher.go#L160

I'm happy to file a PR if we get consensus on which codes we want to retry. Related work:

- https://docs.aws.amazon.com/apigateway/api-reference/handling-errors/
- https://github.com/hashicorp/go-retryablehttp/blob/master/client.go#L424

**Comment by xtreme-sameer-vohra** [comment]
Thanks for filing this @embano1 
Seems pretty reasonable to be more specific. At minimum we should cover the explicit http status checks.

**Comment by benmoss** [comment]
https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry

**Comment by benmoss** [comment]
https://github.com/knative-sandbox/eventing-kafka-broker/blob/3b860bf2870caa2b27e39683d7507fd6dd6cd136/data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/WebClientCloudEventSender.java#L84-L90

https://github.com/knative/eventing/blob/f031ba23b23d20ed8d13491000feb0abcf50d562/pkg/channel/message_dispatcher.go#L312-L315

It seems this might be the standard among implementations right now

**Comment by embano1** [comment]
I wonder why this is overwritten at all and not the default option used? https://github.com/cloudevents/sdk-go/blob/c6de9589bb3578364689adc64414000dabe93c01/v2/protocol/http/protocol.go#L40

This looks like it does what we need (although retrying on 500 would be nice too, I may want to file a PR for the SDK)?

**Comment by benmoss** [comment]
Yeah, it definitely seems like something the sdk should be handling

**Comment by lionelvillard** [comment]
just in case you haven't seen this: https://github.com/knative/eventing/blob/main/pkg/kncloudevents/retries.go

and this: https://github.com/knative/eventing/pull/5285

**Comment by embano1** [comment]
@lionelvillard are you suggesting we should be using kncloudevents as client?

**Comment by lionelvillard** [comment]
I'm just raising awareness, not suggesting anything :-) kncloudevents is meant to be Knative eventing compliant so maybe it makes sense for you to use it.

**Comment by embano1** [comment]
@benmoss thoughts?

**Comment by vaikas** [comment]
@embano1 for the context on why the overrides:
https://github.com/knative-sandbox/eventing-rabbitmq/pull/113

And:
https://github.com/cloudevents/sdk-go/issues/595

Not saying it's correct the way it is, just answering the why :)

**Comment by embano1** [comment]
> Not saying it's correct the way it is, just answering the why :) 

Gotcha! So IMHO we have couple of options here (most, if not all of them breaking):

1) adopt kncloudevents client
1) drop custom retryer in favor of default in ce-client
1) enhance custom retryer as proposed above

**Comment by embano1** [comment]
I agree Ben, we should align with the Knative Eventing spec then - even though I'm not 100% on the same page with some decisions here.

But this also means we have to implement our own retry code mapping [1] since the CloudEvents SDK has a diverging (from the above spec) default:

```go
var defaultRetriableErrors = map[int]string{
	404: "Not Found",
	413: "Payload Too Large",
	425: "Too Early",
	429: "Too Many Requests",
	502: "Bad Gateway",
	503: "Service Unavailable",
	504: "Gateway Timeout",
}
```

[1]
Not sure if there's already a pkg in Knative land which provides these mappings in compliance with the SPEC?
