### ISSUE TITLE
Remove support for Standalone RabbitMQ

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#411]
## Context
Currently, the eventing-rabbitmq integration provides two versions of the RabbitMQ Knative Eventing Broker.
1.  [Standalone RabbitMQ](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#standalone-broker) 
2.  [RabbitMQ operator based Broker](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#rabbitmq-operator-based-broker)

The Standalone Broker utilizes libraries to manage RabbitMQ resources directly. While the Operator based Broker builds on the available RabbitMQ Cluster and Messaging Topology Operators, enabling RabbitMQ resources to be managed via CRDs. Maintaining both requires managing two separate incongruent code paths, which requires extra effort. 

## Change
After a discussion with the RabbitMQ team, we are considering deprecating and eventually removing support for [Standalone RabbitMQ](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#standalone-broker). 

This has the added benefit of allowing us to focus our efforts on making improvements to the [RabbitMQ operator based Broker](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#rabbitmq-operator-based-broker) and you can track the progress [here](https://github.com/knative-sandbox/eventing-rabbitmq/projects/1) 

## Ask
If this impacts you, please provide context on your setup/use case here or on https://github.com/rabbitmq/messaging-topology-operator/issues/135

**Comment by xtreme-sameer-vohra** [comment]
cc @cheskayang since you mentioned y'all are using the Standalone broker [here](https://github.com/knative-sandbox/eventing-rabbitmq/issues/328#issuecomment-853857656)

**Comment by evankanderson** [comment]
https://github.com/knative/community/blob/main/mechanics/SUNSETTING-FEATURES.md provides a guide for what to do in this case.
