### ISSUE TITLE
Implement Metrics for RabbitMQ Eventing pieces

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#415]
**Problem**
Unclear if metrics are present. If they are, what metrics are available ?

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
- Event Producer
- System Operator

### Exit Criteria
- [ ] Users can observe metrics for Eventing RabbitMQ components
- [ ] Document the metrics emitted and setup instructions (referencing [knative.dev](https://knative.dev/docs/eventing/observability/metrics/collecting-metrics/) instructions)

#### Broker
See [Knative Eventing Broker Metrics](https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#knative-eventing-metrics)
- [ ] Ingress
- [ ] Filter
- [ ] Dispatcher

#### Source
See [Eventing Sources Metrics](https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#eventing-sources)
- [ ] Source

#### Additional
- Add reference to RabbitMQ Docs for metrics for the RabbitMQ operators

**Comment by ikvmw** [comment]
**WARNING** I might be terribly wrong.

If I understand correctly eventing provides some sort of middleware - https://github.com/knative/eventing/blob/main/pkg/broker/ingress/ingress_handler.go that implements common logic and offloads implementation specific things to Handler.sender. It's used by in-memory broker here: https://github.com/knative/eventing/blob/main/cmd/broker/ingress/main.go. 

ingress_handler has all necessary metrics baked in. For example https://github.com/knative/eventing/blob/main/pkg/broker/ingress/ingress_handler.go#L238 for `event_dispatch_latencies`.

In rabbitmq broker we don't use ingress_handler and instead have our own handler here: https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/cmd/ingress/main.go. I'm not sure it has any metrics.

What if we will use [ingress_handler](https://github.com/knative/eventing/blob/main/pkg/broker/ingress/ingress_handler.go) too? We will get free metrics and traces.

**Comment by ikvmw** [comment]
I'm feeling brave enough to say metrics are yet to be implemented for ?all? our components. I'm hope it's wrong but I just can't find them :-)

**Comment by ikvmw** [comment]
Had a wonderful call today with @benmoss and @gabo1208. 

The main questions from me were:

1) How we (if we even are) listen to relevant ConfigMaps updates (logging, tracing, metrics)?
**Context:** according to docs (e.g. here https://knative.dev/docs/eventing/observability/metrics/collecting-metrics/) knative services are supposed to apply changes to ConfigMaps on the fly.
**What we learnt:** there is a difference between the way internal knative services managed vs integrations. Our own reconciler propagates ConfigMaps to json-encoded env vars. We _expect_ that reconciler watches for maps and redeploys on changes. We expect that it does like this now. Which means downtime. But for v1 probably ok.

2) How we populate required metrics tags?
**Context:** according to docs (e.g. here https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#broker-ingress) users can expect a number of standard tags across knative landscape. 
**What we learnt:** in-memory broker being multitenant can derive broker name and namespace from requestURI. Other tags, like container and pod_name it gets from the env_vars (yaml). We create deployments programmatically so we can look at two techniques:
    -  propagate tags from reconciler as env vars (look here - https://github.com/knative-sandbox/eventing-rabbitmq/blob/9feb97fed8770d0d5e3c1111a01fe4efc56b2842/pkg/reconciler/broker/resources/ingress.go)
    - use kubernetes downstream API

**Also** we want to get logging, tracing and metrics in sync. We want to look how tracing and logging get pod info and how they communicate with ConfigMaps.

**Comment by salaboy** [comment]
@ikvmw I think we have made huge progress here.. so we just need to update the docs saying that our metrics are covering the metrics described in the spec, which I think we are with our current implementation
