### ISSUE TITLE
Samples on how to use Knative + RabbitMQ

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#416]
Add to [Eventing Samples](https://knative.dev/docs/eventing/samples/)
- [ ] Broker + Trigger sample 
- [ ] Source -> Knative Service sample

Pre-requisite should point to a Operator Based RabbitMQ installation

**Comment by gabo1208** [comment]
I think PR #555 fix this right @xtreme-sameer-vohra?
