### ISSUE TITLE
Document a Trigger's Behavior for FIFO, High Throughput modes

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#424]
Ensure the configuration and expected behavior is documented for end users, specifically
- message channel is rate-limited by the prefetch count, so the number of goroutines will equal the prefetch
- setting prefetch to 1 with no autoscaling would be equivalent of FIFO

**Comment by embano1** [comment]
Related #418

**Comment by embano1** [comment]
Also, autoscaling and its behavior should be documented (i.e. not supported, use KEDA, etc.)

**Comment by embano1** [comment]
Also, document how visibility timeouts (crashed/unresponsive KService) affect ordering due to 10s default hearbeat timeout currently used https://github.com/streadway/amqp/blob/master/connection.go#L133-L136.

**Comment by xtreme-sameer-vohra** [comment]
#### Open question
I am not sure how [requeue](https://github.com/knative-sandbox/eventing-rabbitmq/blob/e4db575945e91966a27894c09927a24014b8fa80/cmd/dispatcher/main.go#L45) impacts behavior. This doesn't appear to be part of the [Knative Delivery Spec](https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md#event-delivery)

If `requeue` set to `true` and delivery keeps failing, will that result in the poison pill scenario ?

**Comment by embano1** [comment]
IMHO `requeue` is an implementation detail to comply with certain retry/redelivery aspects in the SPEC.

**Comment by ikvmw** [comment]
Addition as per call with @embano1 and @xtreme-sameer-vohra.

Clarify queue lifecycle (see Trigger/Dispatcher section in the [doc](https://docs.google.com/document/d/14YArSzMxqivDu80YeRvqHMYdP_ypk0-XWw5sVtiD2L8/edit))

**Comment by xtreme-sameer-vohra** [comment]
Split retry behaviour https://github.com/knative-sandbox/eventing-rabbitmq/issues/592
