### ISSUE TITLE
Do we want to support batch events sending

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#438]
We need to decide if we want to support the CloudEvents batch format or not, and the implement it.

**Comment by benmoss** [comment]
https://github.com/knative/eventing/issues/4409 I don't think eventing generally supports the json batch format

**Comment by gabo1208** [comment]
Yeah this is like a thought of mine based on a TODO, but the solution should be to wait for the sockets implementation?

**Comment by evankanderson** [comment]
I'd prioritize HTTP/2 support first, then measure the improvement batch provides.

**Comment by evankanderson** [comment]
Rationale: HTTP/1.1 Is likely encumbered by a lot of TCP setup/teardown per request, which probably imposes substantial overhead. HTTP/2 allows multiplexing requests over a single TCP pipe for the cost of a library change for clients. Adding batch delivery support requires restructuring code vs current implementations, so has a higher ecosystem cost.

**Comment by gabo1208** [comment]
Nice! Supper clear, thanks @evankanderson
