### ISSUE TITLE
Understand upstream release management & document upgrade process

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#450]
Open Questions
- Release cadence between cluster operator & messaging-topology operator
- CRDs upgrade/conversion contract & expectations [Ref](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#overview)
- What is the upgrade/downgrade experience for users ? This should be documented.

**Comment by gerhard** [comment]
> Release cadence between cluster operator & messaging-topology operator

As far as I know, these are released ad-hoc and independently: any of these operators can be released at any point in time.

This is the only relevant doc that I am aware of which looks somewhat useful: https://github.com/rabbitmq/cluster-operator/blob/c813d56785460dd9ecef7a2423851c90afeeaf4e/docs/proposals/20200806-versioning-release-strategy.md

> CRDs upgrade/downgrade contracts & expectations

I don't know anything about this, but I think that @ChunyiLyu @ansd @MirahImage @mkuratczyk may be able to help.

> What is the upgrade/downgrade experience for users ? This should be documented.

`kubectl apply` and the operator figures out what needs to happen next. I also think that it would be great if this was documented. Maybe someone that I mentioned earlier can add more details 🤔

**Comment by yaronp68** [comment]
the release cadence of OSS operators is currently ad-hoc. We support loose semver so typically no features in patches only in minors.  The APIs are still not GA
Regarding upgrade experience of the operator (and how to decide when to upgrade a cluster) there are docs:
[upgrading the operators](https://rabbitmq.com/kubernetes/operator/upgrade-operator.html)

**Comment by MirahImage** [comment]
The APIs follow the standard K8s convention, in that there will be no breaking changes without a version bump, and there will be backwards compatibility, as outlined in https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the links.
Sounds like there is no coupling between the Cluster operator and Messaging Toplogy operator and eventing-rabbitmq should attempt to bump to their latest versions independently ?

**Comment by xtreme-sameer-vohra** [comment]
> Indeed, that is the case. The coupling between the two operators is only through their public facing APIs, so generally, bumping the two independently should be safe. There are plans to merge the two operators into a single repository to reduce confusion and future-proof this coupling, but you should be safe bumping them independently for now.

That sounds great. Is there a timeline/milestone one can follow ?
