### ISSUE TITLE
[Spike] Do e2e / conformance tests cover the RabbitMQ operator based broker ?

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#452]
Hint: Broker -> spec.config (how it gets the secret has multiple paths and all of these might not be tested eg. cluster-operator-> secret)

**Comment by benmoss** [comment]
We do test the broker workflow passing in the `RabbitMQCluster` object, [this](https://github.com/knative-sandbox/eventing-rabbitmq/blob/e19128bf1ab043af81931004e73a3acd1e90cf68/.github/workflows/kind-e2e.yaml) workflow runs the e2e suite against the operator-based broker. 

If this broker controller receives a broker that doesn't have a `RabbitMQCluster` as it's config it just errors out: https://github.com/knative-sandbox/eventing-rabbitmq/blob/e19128bf1ab043af81931004e73a3acd1e90cf68/pkg/reconciler/broker/broker.go#L124-L129
