### ISSUE TITLE
Multiple Knative Brokers in different namespaces that connect and use a single RabbitMQ cluster instance

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#454]
**Problem**
A user might prefer to create a single RabbitMQ cluster with sufficient capacity to service all messaging needs of a single K8s cluster. It would be desirable to have multiple Knative Brokers (across multiple namespaces such as foo, bar) connect to and use a single RabbitMQ cluster thats created in baz namespace.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
This feature would be used by the K8s Cluster Administrator

**Exit Criteria**
Be able to setup something like
1. Install RabbitMQ operators and eventing-rabbitmq
2. Create RabbitMQ Cluster `my-rabbit-cluster` in namespace `baz`
2. Create a Knative Broker `foo-broker` (backed by `my-rabbit-cluster`) in namespace `foo`
3. Create a Knative Broker `bar-broker` (backed by `my-rabbit-cluster`) in namespace `bar`
4. Ensure the status of both Brokers is `true`
5. Ensure that an event producer (eg. PingSource) can send events to the brokers and an event consumer (eg. event-display) can consume events from the two brokers.

**Comment by gvmw** [comment]
There is another part to this. When the `Exchange` object gets created, it should pick up the `Broker` namespace property.

Given the following `Broker` object:

```yml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: cloudevents-player-rabbitmq
  namespace: cloudevents-player
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmq-knative-eventing
    namespace: knative-eventing
```

This `Exchange` object gets created internally:

```yml
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  creationTimestamp: "2021-10-14T12:38:02Z"
  generation: 1
  labels:
    eventing.knative.dev/broker: cloudevents-player-rabbitmq
  name: b.cloudevents-player.cloudevent800f452d438e304bcd51cc5b6d8c122f
  namespace: cloudevents-player
  ownerReferences:
  - apiVersion: eventing.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Broker
    name: cloudevents-player-rabbitmq
    uid: 48606b0c-66c8-4c27-813e-c667dace1ea0
  resourceVersion: "69707"
  uid: 7ef0e853-779c-4d0b-8078-ee3e0c18e75a
spec:
  durable: true
  name: b.cloudevents-player.cloudevent800f452d438e304bcd51cc5b6d8c122f
  rabbitmqClusterReference:
    name: rabbitmq-knative-eventing
  type: headers
  vhost: /
```

This is what's missing:

```diff
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  creationTimestamp: "2021-10-14T12:38:02Z"
  generation: 1
  labels:
    eventing.knative.dev/broker: cloudevents-player-rabbitmq
  name: b.cloudevents-player.cloudevent800f452d438e304bcd51cc5b6d8c122f
-  namespace: cloudevents-player
+  namespace: knative-eventing
```
