### ISSUE TITLE
Event source should not require declaring the exchange and the queue

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#455]
Right now the event source will [declare an exchange, a queue, and a binding](https://github.com/knative-sandbox/eventing-rabbitmq/blob/95462cfe87b8372512b8f77573e0f47078258477/pkg/adapter/adapter.go#L192-L247). It's possible to specify an existing exchange and queue for the source to use, but it will still redeclare the exchange, queue, and binding.

We should make it possible to skip declaring these resources, since a user may not have permissions to redeclare them, or it may not be possible to redeclare them if they are using options that we don't support.

**Comment by rikatz** [comment]
/assign
@gerhard will take a look here and let you know ! Thanks

**Comment by gvmw** [comment]
Thank you @rikatz 🙌🏻
