### ISSUE TITLE
Bump RabbitMQ Dependencies to latest versions

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#479]
**Problem**
The latest available versions of the RabbitMQ dependencies are
- RabbitMQ Cluster Operator : 1.10.0
- RabbitMQ Messaging Topology Operator : 1.2.1

The versions being tested in the workflows
- RabbitMQ Cluster Operator : 1.8.2
- RabbitMQ Messaging Topology Operator : 0.8.0

This ensures eventing-rabbitmq is compatible with the latest versions of RabbitMQ dependencies

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
Cluster Operators

**Exit Criteria**
Update the following workflows to use the latest versions and ensure they are green
- workflows/kind-conformance.yaml
- workflows/kind-e2e.yaml
- workflows/kind-conformance-standalone.yaml

**Additional context (optional)**
Nice to have: automation to automatically create a PR updating the workflows when a new version is available

**Comment by benmoss** [comment]
https://github.com/knative-sandbox/eventing-rabbitmq/pull/492 did this 

/close
