### ISSUE TITLE
Source should use some kind of backoff

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#504]
I have the source installed and it's failing to deliver messages to its subscriber and it's currently warming up my apartment with its retry rate 😄
![Screen Shot 2021-11-10 at 4 43 47 PM](https://user-images.githubusercontent.com/239754/141198473-03f62b28-d1c0-4ea5-a393-46c36daa153e.png)
 

# Open Question
- Is this change going to be additive or breaking the API ? If its the former and doesn't break the API, lets tackle this post MVP.

**Comment by gabo1208** [comment]
Closed by #614
