### ISSUE TITLE
Make the codecov action suggest, not fail

### ISSUE THREAD

**Issue by gvmw** [knative-sandbox/eventing-rabbitmq#510]
Even though https://github.com/knative-sandbox/eventing-rabbitmq/pull/492 improves codebase coverage by `0.04%`, [`codecov/patch` action is failing](https://github.com/knative-sandbox/eventing-rabbitmq/pull/492/checks?check_run_id=4212877663) because some of the changes are not fully covered. Most of this is the label functions which are now the same across `Exchange`, `Queue` & `Binding`.

Since changing the codecov score wouldn't help, maybe we should change this check to be a suggestion, rather than a pass/fail.

This has all the details: https://app.codecov.io/gh/knative-sandbox/eventing-rabbitmq/compare/492/diff. The [Codecov Delta explanation](https://docs.codecov.com/docs/codecov-delta) helped me understand how to interpret the file scores in the diff.

**Comment by benmoss** [comment]
I was mistaken about this, it's failing because your PR is only 60% covered. It's unfortunate that you're changing lines that previously weren't covered, but I think Codecov is still right to call this out. We can (and do) regularly decide to ignore these failures.
