### ISSUE TITLE
Improve e2e tests running and debugging docs 

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#517]
**Problem**
There is a need to improve the process of running and debugging the e2e tests, there are a lot of env variables and tricks (SYSTEM_NAMESPACE, make the test namespace to persist between run, expose RabbitMQ management UI, etc...)
That are not obvious for new folks wanting to contribute that could be documented to speed up the learning curve into this matter in this repo.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Developers

**Exit Criteria**
A good and complete docs for the eventing-rabbitmq e2e tests

**Comment by KauzClay** [comment]
Hi @gabo1208 , where do you think this document should live? I'm working on it now, and I just made it as a README.md in the test/e2e dir.

**Comment by gabo1208** [comment]
Seems the right place for it to be, and not forget to keep the reference to the knative help docs for more detailed documentation on the whole knative related test setup.

**Comment by gvmw** [comment]
I think @gabo1208 that #525 addresses part of the problem. To try it out, given a vanilla host with `make` & `go` installed - I recommend a plain Linux VM - run `make e2e-setup test-e2e` and see what happens. My expectation is that everything will just work.

> Tip: `make` will show you what targets are available.

I still think we should merge #529, but my understanding is that the setup is the biggest struggle, as well as the fact that https://github.com/knative/eventing/blob/main/test/README.md#e2e-tests differs from what runs in GitHub Actions. As much as I like scripts - [I really do](https://gerhard.io/talk/tdd-bash/) - I think that #525 is a better approach that will take little effort to integrate with GitHub Actions. Yes, I volunteer to do that too, as well as update the e2e test doc that will be merged part of #529 to reflect this new approach.

Try it out and let me know how well it works for you. A Mac with `brew` & `go` installed will also work.
