### ISSUE TITLE
What is a good default production-ready RabbitMQ cluster?

### ISSUE THREAD

**Issue by gvmw** [knative-sandbox/eventing-rabbitmq#518]
We have been talking with @xtreme-sameer-vohra @benmoss @gabo1208 and @salaboy what a default production-ready RabbitMQ cluster may look like in the context of **eventing-knative**. This was a follow-up to [Eventing RabbitMQ Delivery Semantics](https://docs.google.com/document/d/14YArSzMxqivDu80YeRvqHMYdP_ypk0-XWw5sVtiD2L8/edit) started with @embano1.

We have touched up on the following:

### Cluster size

The default RabbitMQ cluster size in eventing-rabbitmq is single node. All documentation, testing and even performance benchmarks - https://github.com/knative-sandbox/eventing-rabbitmq/blob/c79d3aa6c6241bd72f907fe0bce81d158a1a1794/test/performance/broker-rmq/README.md - use this.

While this is great when getting started, the official recommendation is a minimum of 3 nodes: https://rabbitmq.com/production-checklist.html#distribution-considerations-cluster-size.

There is a related [Production Example](https://github.com/rabbitmq/cluster-operator/blob/a7fb232bf78c5ce735294ccc49da793a6d585ee9/docs/examples/production-ready/README.md) documentation in the **rabbitmq/cluster-operator** repository which may prove to be useful for this conversation.

### Queue Type

The default is classic durable queue with message persistence.

I was mentioning that a [Quorum Queue](https://rabbitmq.com/quorum-queues.html) is a likely better default choice. Even if a 3-node cluster is used, all non-replicated queues will be unavailable for the entire duration of their node unavailability. This means that just a subset of queues will be unavailable (requires queues to be spread across all nodes in the cluster), which is better than all of them being unavailable (the single-node scenario above). In terms of tradeoffs, quorum queues use more memory than classic queues, and we also know that 10k quorum queues is too many for a single RabbitMQ cluster (the cost of consensus is too high).

[Streams](https://rabbitmq.com/streams.html) were also mentioned in terms of the "queue" with lowest overhead and highest throughput, but their behaviour differs from the typical RabbitMQ queue and may not be what we are looking for in this context. It's still worth mentioning them as they are the future building block of RabbitMQ streaming, which fits well in the Knative eventing ecosystem.

### `Broker` / `Trigger` properties

Rather than exposing RabbitMQ-specific properties to eventing-rabbitmq users, my proposal was to consider wrapping cluster sizing and queue type in more generic properties, like `ha` or `replication-factor` and perform the translation to RabbitMQ translation internally. In this context, @xtreme-sameer-vohra was wondering whether these annotations would be declared on the `Broker` level, and then propagate through all associated objects, like `Triggers`, `Sinks`, etc.

---

**What happens next?**

- [x] Share on knative.slack.com #eventing & #eventing-rabbitmq and ask for input
- [ ] Document a default production-ready RabbitMQ cluster (include a manifest, similar to [rabbitmq/cluster-operator/docs/examples/production-ready/rabbitmq.yaml](https://github.com/rabbitmq/cluster-operator/blob/a7fb232bf78c5ce735294ccc49da793a6d585ee9/docs/examples/production-ready/rabbitmq.yaml))
- [ ] Learn what is a good production-ready RabbitMQ cluster for @embano1
- [ ] Maybe document this real-world use case ☝🏻

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the detailed context @gvmw 

> I was mentioning that a Quorum Queue is a likely better default choice. Even if a 3-node cluster is used, all non-replicated queues will be unavailable for the entire duration of their node unavailability.

That seems to be a pretty compelling reason for enabling eventing-rabbitmq user's to leverage Quorum Queues or even having them be the default queue type.

> In terms of tradeoffs, quorum queues use more memory than classic queues

Do we know how much more memory ? 
Noob question, in the case of a single node cluster, is a Quorum Queue == Classic Queue ? 

> and we also know that 10k quorum queues is too many for a single RabbitMQ cluster (the cost of consensus is too high).

Currently, without a dead letter sink configured, there would be 1 queue created for every Trigger. With a dead letter sink configured on a Trigger, there would be 2 queues for every Trigger. A limit of ~5K triggers is worth documenting but doesn't sound like a blocker. 

>Rather than exposing RabbitMQ-specific properties to eventing-rabbitmq users

Definitely makes sense to reduce the cognitive load. Could we go a step further and not require application developers to have to know/worry about this at all or is there a reason why application developers should have to make this choice? Conversely, the cluster operators are likely to have opinions and we should give them the ability to configure the properties.

**Comment by gvmw** [comment]
> That seems to be a pretty compelling reason for enabling eventing-rabbitmq user's to leverage Quorum Queues or even having them be the default queue type.

Yes, I think so too. I also think that @kjnilsson will be most interested in this use-case.

> Do we know how much more memory ?

It depends on message size, throughput & replication factor as well as `x-max-in-memory-length` and/or `x-max-in-memory-bytes` **across all quorum queues**.

Out of the box, RabbitMQ nodes are expected to have 2GB memory just for the RA WAL: https://rabbitmq.com/quorum-queues.html#resource-use . This is one of the reasons why [our production-ready example](https://github.com/rabbitmq/cluster-operator/blob/a7fb232bf78c5ce735294ccc49da793a6d585ee9/docs/examples/production-ready/README.md) starts at 10Gi memory & 4CPUs (virtual CPUs, the cloud norm, are OK).

> Noob question, in the case of a single node cluster, is a Quorum Queue == Classic Queue ?

They behave like Classic Durable Queues, and I'm not sure if they use the WAL if there are no replicas. For a production deployment of eventing-rabbitmq, my default queue type recommendation would be Quorum Queue.

> Currently, without a dead letter sink configured, there would be 1 queue created for every Trigger. With a dead letter sink configured on a Trigger, there would be 2 queues for every Trigger. A limit of ~5K triggers is worth documenting but doesn't sound like a blocker.

I would play this safe and set and recommend 1K triggers. We wouldn't want a slow cluster, and 2K quorum queues sounds like a comfortable upper limit. I would be most comfortable if we recommend what we benchmarked and proved that works. Number of clients, message payloads and the replication factor, as well as multiplexing (message fan-out scenarios) can play a significant role in this. Networks and disks (SSDs can be slow in the cloud) can make a big difference, which is why a canonical example like the Production ready one, is really helpful when reasoning about limitations. While this has not changed in years, it captures well the point that I'm trying to make here: https://github.com/rabbitmq/workloads

> Definitely makes sense to reduce the cognitive load. Could we go a step further and not require application developers to have to know/worry about this at all or is there a reason why application developers should have to make this choice? Conversely, the cluster operators are likely to have opinions and we should give them the ability to configure the properties.

I can imagine application developers that know RabbitMQ and will want to make this choice, but based on my experience, the majority doesn't care: they just want safe defaults that work as advertised. Most surprises come from unrealistic expectations, and not stating what can be expected from the default configuration, and just letting users figure it out creates massive headaches for everyone. After 5-6 years of fighting on this hill, I can see where this is going ⛰️

**Comment by embano1** [comment]
+1 on using quorum queues by default (unless there's a strong reason against it in favor of classic durable queues)

+1 on upper limit of 1k triggers. Users can always deploy a separate RMQ cluster/broker to increase capacity/throughput if needed.

**Comment by kjnilsson** [comment]
What is a trigger (from a RabbitMQ POV)? a consuming application?

What is the expected throughput of a trigger and what would the average message size be? Do all trigger queues need to have their own dlx queue or could this be shared across the vhost? How are the dead-letters consumed? Could the dead-letter queue be a shared stream?

If the throughput isn't likely to be very high you could try to configure a lower WAL to reduce peak memory use.

We've done some optimisations recently around running many quorum queues, 2k seems like a comfortable limit but you can probably stretch this a bit further unless the total throughput is high.

In addition to setting `x-max-in-memory-length=0` I also recommend setting `x-max-length` as well as `x-delivery-limit` to avoid excessive backlogs and processing attempts. See: https://gist.github.com/kjnilsson/4a681bedd17c33c09220f97c7c2a0dcf

**Comment by embano1** [comment]
> What is a trigger (from a RabbitMQ POV)? a consuming application?

Yes, code see here: https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/dispatcher/dispatcher.go

> Do all trigger queues need to have their own dlx queue or could this be shared across the vhost?

Both is possible, though the common approach seems to be a shared DLQ used in Knative triggers.

**Comment by gvmw** [comment]
> @kjnilsson: What is a trigger (from a RabbitMQ POV)? a consuming application?

Yes.

> @kjnilsson: What is the expected throughput of a trigger and what would the average message size be?

This is difficult to answer, even as an estimation. To put it in a different form, I want to drive my car as fast as it's safe and legally allowed to. In this car <-> RabbitMQ analogy, what I am really interested in is the top speed that the car (RabbitMQ) can achieve.

Let's assume that messages are 10KiB in size and replication factor is 3. We already have the 2k quorum queue limit. For simplicity, we can use 1 publisher & 1 consumer per quorum queue. Does this sound like a realistic real-world scenario @embano1 for you?

> @kjnilsson Do all trigger queues need to have their own dlx queue or could this be shared across the vhost?

I am not sure, but I would guess that each queue gets its own dlx queue.

> @kjnilsson: How are the dead-letters consumed?

Ad-hoc, most likely getting dropped as a result of hitting the queue length limit, which should be set by the way - we have not discussed this yet.

> @kjnilsson: Could the dead-letter queue be a shared stream?

That is an interesting proposition which is likely to generate more questions. In the interest of keeping the first iteration simple, I would propose not.

> @kjnilsson: If the throughput isn't likely to be very high you could try to configure a lower WAL to reduce peak memory use.

Yes, that is a very good idea. When you say "high throughput" what do you have in mind in terms of messages / second & message payload?

> @kjnilsson: We've done some optimisations recently around running many quorum queues, 2k seems like a comfortable limit but you can probably stretch this a bit further unless the total throughput is high.

What number do you have in mind when you think "high total throughput"?

> @kjnilsson: In addition to setting `x-max-in-memory-length=0` I also recommend setting `x-max-length` as well as `x-delivery-limit` to avoid excessive backlogs and processing attempts. See: https://gist.github.com/kjnilsson/4a681bedd17c33c09220f97c7c2a0dcf

This is great, thank you!

A few follow-up questions came up today when we were discussing this. These are my top ones:

1. If we continue with classic queues, what does the upgrade to quorum queues look like?
2. Does it make sense to use quorum queues if we default to a single node?
3. Should we enforce a queue limit if we use quorum queues?

I think that the above deserve a discussion since there is a lot more to it. Reaching out privately so that we can leverage that high-bandwidth, synchronous communication and capture the conclusions here, rather than continuing with GitHub 🏓

**Comment by gvmw** [comment]
This is what we came up with @kjnilsson.

This will need to be benchmarked, but it's a starting point for a production-ready default:

- 3-node cluster
  - 4 vCPUs
  - 10GiB
  - 500GiB SSD disks - on GCP this translates to max. X IOPS & X MB/s throughput (throughput is more important than IOPS by the way)
- `autoheal` if there is no object churn, otherwise `pause_minority`
- quorum queues with 3 replicas each and the following properties set via a policy (not queue arg. because PR #N)
   - `max-in-memory-length=0` doesn't keep any messages in limit
   - `max-length=10000` <- is a limit of 10k messages enough? we are assuming that messages are at most 10KiB (common JSON payload), but it may need changing based on memory / disk etc. available
   - `overflow=reject-publish` so that new messages are reject if the limit is reached (no existing messages will be dropped)
   - `delivery-limit=10` poison message handling, same setting as Azure Service Bus <- this can be lowered or increased based on the use-case, but it's worth setting this regardless
- limit quorum queues to 5000
- maybe disable management metrics: https://www.youtube.com/watch?v=NWISW6AwpOE
- limit connections to 10k per node (30k in total across the entire cluster) <- this is here as a conversation starter, not a definitive number
- limit channels to 10k per node (30k in total across the entire cluster) <- ideally, there will be a single channel per connection. This is here as a conversation starter, not a definitive number

**Comment by xtreme-sameer-vohra** [comment]
Thanks @gvmw @kjnilsson 

> @kjnilsson Do all trigger queues need to have their own dlx queue or could this be shared across the vhost?
> I am not sure, but I would guess that each queue gets its own dlx queue. Maybe @xtreme-sameer-vohra or @benmoss can add more nuance to this. @embano1 is Customer 0 in my mind, so he might be able to chime in.

This is configurable by the user. They can
- configure it on a Knative Broker. All Triggers that don't specify their own will share the Broker's dlx queue ( N queues : 1 DLX queue)
- configure it on a Trigger. This Trigger's queue would get its own dlx queue (1 queue: 1 DLX queue)
[Diagram](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md)


Were these discussed ?
> A few follow-up questions came up today when we were discussing this. These are my top ones:
> If we continue with classic queues, what does the upgrade to quorum queues look like?
This may impact what would be in scope for MVP vs what we'd want to tackle subsequently
> Does it make sense to use quorum queues if we default to a single node?
It would be useful to understand if folks can still use a single node setup and not lose messages that have been accepted. The caveat being lack of HA (which might be acceptable in certain scenarios)
