### ISSUE TITLE
Create a Architecture Diagram

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#520]
**Problem**
An architecture diagram/documentation that allows an eventing-rabbimq user to 
- understand all the internal resources (queue, exchange, etc) created and who owns them (lifecycle) when they create a Source | Broker | Trigger 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
Cluster Operator & Application Developer

**Exit Criteria**
- A user knows the internal resources created and know which user facing resources they belong to.
- Annotations to know at which step we have delivery retries setup
- Annotations to know concurrency settings  in any message handling component (eg. Go routines in the dispatcher, Go routines in the ingress)

References
- https://docs.google.com/drawings/d/1PB5-wo1cag-QnlJIBMJXu-3l2tPzXBza3PMaJlexdmM/edit
- https://docs.google.com/document/d/1LjcpCMAeoAg5qgQqksCGadIpSLpRL29ffiSL_4Bx3wQ/edit#heading=h.z45ihil7yf9

**Comment by gabo1208** [comment]
Here are the image links:
- https://drive.google.com/file/d/13nnL9AHMinZMYjX_NhJF-CTOb574B3VL/view?usp=sharing
- https://drive.google.com/file/d/1yF6knLFP2iBLV1HMyxBWj7sJ_vIxT8G3/view?usp=sharing
