### ISSUE TITLE
Context setting is not affective in dispatcher

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/eventing-rabbitmq#523]
This line is a no-op: https://github.com/knative-sandbox/eventing-rabbitmq/blob/c181b1443f6e2b4ca6c2b9578bd13d0c52a800d5/pkg/dispatcher/dispatcher.go#L166

Suggested solution: remove line and use the delivery settings configured in earlier steps in the dispatcher **unless** we want different delivery semantics for sending responses to the broker. Not sure if that's a valid use case (and covered in the spec) or would rather confuse users.

**Comment by benmoss** [comment]
I think the context still has the delivery settings from https://github.com/knative-sandbox/eventing-rabbitmq/blob/e2751827d7f740a148a2643daecb83a6032061c3/pkg/dispatcher/dispatcher.go#L146-L150, so I don't think there's any change other than deleting this dead code

**Comment by benmoss** [comment]
Oh never mind, I guess with how this works the retries might have been used up by the previous request. So this must have been an attempt to reinitialize the retry count.

**Comment by embano1** [comment]
> Oh never mind, I guess with how this works the retries might have been used up by the previous request. So this must have been an attempt to reinitialize the retry count.

 Yeah, just that ctx is never updated/assigned to that call, hence ineffectual.
