### ISSUE TITLE
Broker ingress does not reconnect if connection to the RMQ is lost

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#534]
**Describe the bug**
If for some reason the ingresses' connection to the RabbitMQ server is lost, it will go into a permanent failure loop.

 **Expected behavior**
It should either exit on failure and allow k8s to restart it or re-establish the connection.

 **To Reproduce**
- Deploy a broker/trigger topology ([for example](https://gist.github.com/benmoss/a32017ec40eb22c53191c462c5d3f2db))
- Determine the ingress pods IP via `kubectl get pods -o wide`
- Go into the RMQ management dashboard, go to the "Connections" tab, select the connection with the matching IP, and manually close the connection via "Force Close" at the bottom:
![Force close connection](https://user-images.githubusercontent.com/239754/144621179-b5a90612-e9d6-4604-b5f1-3df9ded3b3b1.png)
- Observe that the ingress goes into a failure loop, with a particularly [unhelpful error message](https://github.com/knative-sandbox/eventing-rabbitmq/blob/4cf1cf0762a981a23813b3170a48ff538df32776/cmd/ingress/main.go#L147). We should log the RabbitMQ `err` here for better troubleshooting in the future.

 **Knative release version**
Deployed from main branch

 **Additional context**
This is the error it'll continually log:
```json
{"level":"error","ts":1638542285.9604282,"logger":"fallback","caller":"ingress/main.go:119","msg":"failed to send event,failed to publish message","stacktrace":"main.(*envConfig).ServeHTTP\n\tknative.dev/eventing-rabbitmq/cmd/ingress/main.go:119\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\tgo.opencensus.io@v0.23.0/plugin/ochttp/server.go:92\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/network/handlers/drain.go:104\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2878\nnet/http.(*conn).serve\n\tnet/http/server.go:1929"
```

**Comment by gabo1208** [comment]
One question I have here, should it try to reconnect? Or logging the error is enough?

**Comment by gabo1208** [comment]
Divided into two tasks:
- [ ] Improve logging ← currently finishing this, I'll update this issue with the progress
- [ ] Handle reconnection tries
