### ISSUE TITLE
There is no failover or protection when events fail to be sent from the RabbitMQ Source

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#537]
**Describe the bug**
When there is an error sending the events from the Source to a Sink they just keeps getting reqeued and RabbitMQ goes crazy:

<img width="1104" alt="screenshot_2021-12-02_at_15 58 22" src="https://user-images.githubusercontent.com/4516177/144662159-f6666963-3a1f-41fb-9a4d-f5ca00bc9be8.png">

When the peak in message rate in the graph starts to go down is when we configured the Knative DNS in the Cluster.

 **Expected behavior**
When message are not been sent, that the Source stops and wait for the Sink to be available. And maybe that the source (if the sink is a Ref) checks that a resolvable Ref.

 **To Reproduce**
- Spun up a Cluster environment with knative, but do not configure the DNS
- Create a RabbitMQ cluster
- Create a Source with a sink (uri or ref)
- Create the sink (optional)
- Get to the RabbitMQ Management UI and see how the image above gets replicated

 **Knative release version**
1.0.0

**Comment by gabo1208** [comment]
I'm thinking of implementing the same strategy as the Broker's dispatcher, don't know what you all think @ikvmw @xtreme-sameer-vohra @benmoss. Even when that imply giving an extra (no-required) argument to the source config

**Comment by xtreme-sameer-vohra** [comment]
@gabo1208 Could you expand on what you mean as the same strategy as the Broker's dispatcher ?

**Comment by gabo1208** [comment]
![image](https://user-images.githubusercontent.com/4516177/155171741-35741db3-34a3-4017-90f4-e313d2bba7e5.png)
Here is the same case with no Requeue, using CloudEvents HTTP retries + backoffPolicies

**Comment by xtreme-sameer-vohra** [comment]
Hey @gabo1208 is this the same as https://github.com/knative-sandbox/eventing-rabbitmq/issues/504 ?

**Comment by gabo1208** [comment]
Yep it is @xtreme-sameer-vohra ! I missed that one
