### ISSUE TITLE
At least once delivery semantics

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#540]
**Problem**
System Operators would like to provide a platform to Application Developers with `at least once` delivery semantics. 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
- **Event Consumer(Application Developers)** - using Knative Eventing
- **System Operator** - providing the platform to Event Consumers (Application Developers)

**Exit Criteria**
Ensure `at least once delivery` of messages through the system.
Document the configuration to achieve `at least once delivery` and the conditions (retries, timeouts, etc) that impact it.

**Additional context (optional)**
### Broker to Sink
[Ref Diagram](https://docs.google.com/drawings/d/1PB5-wo1cag-QnlJIBMJXu-3l2tPzXBza3PMaJlexdmM/edit)
- [ ] Broker Ingress 
  - [x] #334
  - [ ] #645
- [x] RabbitMQ Core (Exchange to Queue)
- [ ] Trigger/Dispatcher
  - [x] #424
  - [x] #592
  - [ ] #519 
  - [x] #591 
- [x] #719 

### Source to Sink
- [x] Source/Adapter #504 | #537 

### More context
A [good read](https://medium.com/geekculture/aws-lambda-and-sqs-what-nobody-tells-you-about-their-mix-c9e4631dbb0f) from a user's perspective of working with managed services without clear documentation and having to discover behavior manually. This issue should remove the need for an end user to have to figure it out themselves. Thanks for the reference @embano1

**Comment by embano1** [comment]
Regarding timeouts: IIUC several components, e.g. `dispatcher` do not explicitly specify an `http.Client` when constructing a `cloudevent` client. For example: https://github.com/knative-sandbox/eventing-rabbitmq/blob/d5df3042373be340cdaff06025eaf656b4f5f7d8/pkg/dispatcher/dispatcher.go#L77

IMHO this leads to using the default `http.Client` from Go `net/http` which does not enforce **any** timeout.
