### ISSUE TITLE
Broker should use binary mode CloudEvents

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#545]
**Problem**
We're using structured CloudEvents, which requires the dispatcher to read the body of the RabbitMQ message and deserialize it into a CloudEvent. If we published binary mode CloudEvents into Rabbit then we could dispatch them to the sink without needing to do any deserialization, which should increase the performance of the dispatcher.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System operator

**Exit Criteria**
We should see CPU utilization of the dispatcher go down.

**Time Estimate (optional):**
3 days?

**Additional context (optional)**
@gabo1208 recently did some work for the Source that allowed handling both structured and binary mode messages, we should be able to take advantage of that here

**Comment by gabo1208** [comment]
This shouldn't be on the MVP right @benmoss ? Cause with the profiling the conclusion was that is not affecting that much the performance

**Comment by benmoss** [comment]
yeah I don't think this is as important as I thought, my hypothesis seems to have been wrong

/close
