### ISSUE TITLE
Add upgrade tests

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#564]
Eventing core has [upgrade tests](https://github.com/knative/eventing/blob/main/test/upgrade/README.md), we should figure out how to set these up for an eventing-rabbitmq cluster.

**Comment by salaboy** [comment]
@gab-satchi I am ok with leaving this for post MVP, but since you have been looking at the e2e tests and conformance.. It feels like we should re evaluate this one.
