### ISSUE TITLE
Clearly state supported RabbitMQ (topology) operator and server versions

### ISSUE THREAD

**Issue by ikvmw** [knative-sandbox/eventing-rabbitmq#573]
**Problem**
Currently it's not clear (or even unstated) what versions of RabbitMQ operators and server we support. This makes usage/upgrades unnecessary confusing.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System Operator

**Exit Criteria**
We want to have a version matrix that tells which versions of what we support. We want to actually run our tests using those versions, therefore the version matrix can be automatically generated from pipeline spec (or tests outcome, depending on what we want to show - the actual state of things or what we want).

NOTE: Operators and broker work with different faces of RabbitMQ - management and data respectively so it's totally possible that they have different version requirements.

**Comment by salaboy** [comment]
@ikvmw after the team discussions with @ChunyiLyu I think we now know which is the operator we will promote? 
Also after @gab-satchi removed the standalone code.. I think this is way much clear now.. is it just a matter of documenting this with a single line in the docs?
