### ISSUE TITLE
Double check our default settings

### ISSUE THREAD

**Issue by ikvmw** [knative-sandbox/eventing-rabbitmq#574]
**Problem**
We want to make sure we ship optimal and predictable experience out of the box. Let's not surprise people with promising at least once delivery and retry_count set to 0 by default.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
I believe this concerns everybody.

**Exit Criteria**
Just go thru the code, yamls, look at shipped artifacts, make sure we ship sane defaults.

**Comment by ikvmw** [comment]
**Triggers**

For Trigger own dispatcher the default RetryCount is set to 5 off triger has Delivery section: https://github.com/knative-sandbox/eventing-rabbitmq/blob/dcf9a44dcfd50ed36c21bfee80b69e07ad843101/pkg/reconciler/trigger/resources/dispatcher.go#L97

That Delivery section should look like here:
https://knative.dev/docs/eventing/broker/example-mtbroker/

Same applies to standalone Trigger's dispatcher: https://github.com/knative-sandbox/eventing-rabbitmq/blob/dcf9a44dcfd50ed36c21bfee80b69e07ad843101/pkg/reconciler/triggerstandalone/resources/dispatcher.go#L121

**Brokers**

Broker owned Dispatchers don't look for Delivery at all, therefore RetryCount seems to be unset (or 0, depending on what evnconfig puts as default for ints).


**What's interesting**

All this was done via single merge request:
https://github.com/knative-sandbox/eventing-rabbitmq/pull/97
Broker's Dispatcher
https://github.com/knative-sandbox/eventing-rabbitmq/commit/cba1e5d8e04ba303188993b9c3d57dad5acd6880#diff-7ea6105b1ffd2421ccefc526f7b4a309f180c326edb52fd16e7903ae71f4ad78R77
Trigger's Dispatcher
https://github.com/knative-sandbox/eventing-rabbitmq/commit/cba1e5d8e04ba303188993b9c3d57dad5acd6880#diff-55c134604d7e116d75286273d97fb0b8e7d5ef6548c08ff23392dd80946b1eaaR108

**Conclusion**

Looks like for broker-level DLQ Dispatcher we don't set RetryCount.

**Comment by ikvmw** [comment]
https://knative.dev/docs/eventing/event-delivery/

**Comment by ikvmw** [comment]
OTOH this document https://docs.google.com/document/d/1LjcpCMAeoAg5qgQqksCGadIpSLpRL29ffiSL_4Bx3wQ/edit# says: 

```
If the Trigger has DeadLetterSink specified (meaning that it overrides the Brokers destination for unprocessed events
```
From here one can assume `Broker.delivery` is indeed the default for all Triggers. Which leaves as without the way to set `retries` for delivery dead-lettered events.

**Comment by gab-satchi** [comment]
From the control-plane [spec](https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md)

`
If delivery of the dead-letter event fails with a retryable error, the delivery to the deadLetterSink SHOULD be retried up to retry times, following the backoffPolicy and backoffDelay parameters if specified. Alternatively, implementations MAY use an equivalent internal mechanism for delivery (for example, if the ref form of deadLetterSink points to a compatible implementation).
`

**Comment by xtreme-sameer-vohra** [comment]
@ikvmw could you file a separate issue for `Looks like for broker-level DLQ Dispatcher we don't set RetryCount.`, we'd want to tackle that based on your learnings.

**Comment by xtreme-sameer-vohra** [comment]
@ikvmw are there remaining areas we need to double check default settings to complete this exploration issue ?
