### ISSUE TITLE
Let's have more domain-specific metrics!

### ISSUE THREAD

**Issue by ikvmw** [knative-sandbox/eventing-rabbitmq#576]
**Problem**
"Standard" knative metrics are useful but don't give too much insight into the underlying system. RabbitMQ on the other hand can give too much. Let's have our own metrics for knative-managed resources. For example DLQ size, our "normal" queues and so on.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System Operator/Developer

**Exit Criteria**
More domain-specific metrics.

**Comment by xtreme-sameer-vohra** [comment]
@ikvmw  Lets define all the domain specific metrics we'd want to capture prior to tackling this.
