### ISSUE TITLE
Define schema for rabbitmqsources.sources.knative.dev

### ISSUE THREAD

**Issue by ChunyiLyu** [knative-sandbox/eventing-rabbitmq#581]
**Problem**

No actual schema is defined for `rabbitmqsources.sources.knative.dev` at the moment. CRD has `x-kubernetes-preserve-unknown-fields` set to true. See: https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/config/source/300-rabbitmqsource.yaml#L41

**Exit Criteria**

After installing `rabbitmqsources.sources.knative.dev` CRD, I can see information about its schema when I run `kubectl describe crd rabbitmqsources.sources.knative.dev`

**Time Estimate (optional):**

1 - 2?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by ChunyiLyu** [comment]
As first step, I created PR: https://github.com/knative-sandbox/eventing-rabbitmq/pull/586 to 1) remove openapi-gen annotation 2) use the schema tool and generate a schema

That's not all. We have plenty of fields that uses format `_` rather than camel casing which is not to k8s convention (e.g. https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/apis/sources/v1alpha1/rabbitmq_types.go#L74). Field names should be reconsidered as well (e.g. https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/apis/sources/v1alpha1/rabbitmq_types.go#L99 why not name it autoDelete? Which is a known rabbitmq property). In addition to that, I think we should look into whether `rabbitmqsources` queueConfig and exchangeConfig could directly imbed queue spec and exchange spec from topology operator.

**Comment by ChunyiLyu** [comment]
**Investigation on using controller-gen**

I tried using controller to generate rabbitmqsource crd. It does not work because of `spec.sink` which is type `*duckv1.Destination` and `status` which is `duckv1.SourceStatus`. Reason being both of them have `*apis.URL` as one of their fields. `apis.URL` is a knative type alias on `url.URL`. `url.URL` is a struct with no JSON tag specified, so controller-gen cannot successfully parse it.

Related issues reported from others in knative community:
- https://github.com/kubernetes-sigs/controller-tools/issues/625

Error from running controller gen:
```
controller-gen crd paths="./pkg/apis/sources/v1alpha1/" output:crd:artifacts:config=config/source
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:359:2: encountered struct field "Scheme" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:360:2: encountered struct field "Opaque" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:361:2: encountered struct field "User" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:362:2: encountered struct field "Host" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:363:2: encountered struct field "Path" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:364:2: encountered struct field "RawPath" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:365:2: encountered struct field "ForceQuery" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:366:2: encountered struct field "RawQuery" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:367:2: encountered struct field "Fragment" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:368:2: encountered struct field "RawFragment" without JSON tag in type "URL"
knative.dev/eventing-rabbitmq/pkg/apis/sources/v1alpha1:-: conflicting types in allOf branches in schema: object vs string
Error: not all generators ran successfully
run `controller-gen crd paths=./pkg/apis/sources/v1alpha1/ output:crd:artifacts:config=config/source -w` to see all available markers, or `controller-gen crd paths=./pkg/apis/sources/v1alpha1/ output:crd:artifacts:config=config/source -h` for usage
make: *** [manifests] Error 1
```

**Fix**
To be able to use controller-gen, we need to add a kubebuilder go marker to knative type `apis.URL`. I've created a PR: https://github.com/knative/pkg/pull/2431 and it's waiting for review. After this PR is merged in upstream, we will be able to use controller-gen for our CRD generation (and any other CRD that uses `apis.URL` will work with controller-gen as well).

**Comment by gab-satchi** [comment]
Thanks for the work on this. Closing as the CRD is better defined/documented now. re-open if necessary.
