### ISSUE TITLE
Fix Conformance testing

### ISSUE THREAD

**Issue by ikvmw** [knative-sandbox/eventing-rabbitmq#588]
**Describe the bug**
As of now I see that conformance test likely not pass on GH and locally inside kind

 **Expected behavior**
Robust conformance tests

 **To Reproduce**
`make test-conformance`

**See also**
https://github.com/knative-sandbox/eventing-rabbitmq/runs/4909441208?check_suite_focus=true#step:6:2798
https://github.com/knative-sandbox/eventing-rabbitmq/runs/4888976730?check_suite_focus=true#step:6:2869

**Comment by ikvmw** [comment]
What we have found with @gsatchi 1) There is potentially a huge resource leak while running e2e and/or conformance tests via make locally 2) since https://github.com/knative-sandbox/eventing-rabbitmq/pull/567 master doesn't flake but continuously and reliably red. The PR was red itself. Basically our process allowed our team to merge red PRs. I assume that it happened because conformance tests are known to be flaky and well the usual outcome - ignoring. EDIT: link to our commits, note build status: https://github.com/knative-sandbox/eventing-rabbitmq/commits/main

**Comment by xtreme-sameer-vohra** [comment]
Closing this as we're going to explore individual failures separately
