### ISSUE TITLE
Status for for rabbitmqsources.sources.knative.dev

### ISSUE THREAD

**Issue by ChunyiLyu** [knative-sandbox/eventing-rabbitmq#593]
**Problem**

`rabbitmqsources.sources.knative.dev` status field is current empty. We should come up with a reasonable status (and condition) for this CRD. If we think that the status of the adapter deployment is a good enough indicator, we should document that. 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**

System Operator and Developer

**Exit Criteria**

**Comment by gab-satchi** [comment]
closing as we have status with conditions set now. 

/close
