### ISSUE TITLE
Add support for "Prefer: reply" to Broker

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#607]
Spec - https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#derived-reply-events

**Comment by gab-satchi** [comment]
/reopen
/remove-lifecycle stale

We currently attempt to deliver any non empty response back to the sender regardless of the `Prefer: reply` and status code (as long as it's 2xx). Should be updated to follow the rules outlined in the spec.
