### ISSUE TITLE
Better naming for parallel worker count

### ISSUE THREAD

**Issue by ChunyiLyu** [knative-sandbox/eventing-rabbitmq#615]
**Problem**

Better naming for RabbitmqChannelConfig.PrefetchCount.

[Consumer Prefetch](https://www.rabbitmq.com/consumer-prefetch.html) is a known concept in RabbitMQ itself. We need a better name for this configuration so users won't conflate it with RabbitMQ prefetch.

Related issue: https://github.com/knative-sandbox/eventing-rabbitmq/issues/609

**Comment by embano1** [comment]
Full ack! How about something `concurrency` or `parallelism`?
