### ISSUE TITLE
RMQ Queue Type for Triggers

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#658]
**Problem**
From #518 by Gerhard L 

The default is classic durable queue with message persistence.

I was mentioning that a [Quorum Queue](https://rabbitmq.com/quorum-queues.html) is a likely better default choice. Even if a 3-node cluster is used, all non-replicated queues will be unavailable for the entire duration of their node unavailability. This means that just a subset of queues will be unavailable (requires queues to be spread across all nodes in the cluster), which is better than all of them being unavailable (the single-node scenario above). In terms of tradeoffs, quorum queues use more memory than classic queues, and we also know that 10k quorum queues is too many for a single RabbitMQ cluster (the cost of consensus is too high).

[Streams](https://rabbitmq.com/streams.html) were also mentioned in terms of the "queue" with lowest overhead and highest throughput, but their behaviour differs from the typical RabbitMQ queue and may not be what we are looking for in this context. It's still worth mentioning them as they are the future building block of RabbitMQ streaming, which fits well in the Knative eventing ecosystem.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
System Operator

**Exit Criteria**
Resolve Open Questions & create new issues for Action Items

- [x] Is [this](https://github.com/knative-sandbox/eventing-rabbitmq/issues/518#issuecomment-993681431) the recommended queue setup from RMQ ? `max-in-memory-length=0` will be set to limit in memory storage for versions < 3.10. `overflow=reject-publish` and `max-length=10000` will also be set. `delivery-limit` isn't needed as we use the Triggers deliverySpec to prevent perpetual requeuing
- [x] Default Queue Type for Triggers
  - [x] If Quorum Queues
  	- [x] what should the replication factor be ? 3 should be the default replication factor set since the recommendation for a production cluster is also 3 nodes. This value may become configurable in the future if user's request for it.
  	- [x] should we enforce limit on number of queues ? Not as a part of setting default queue type. A lot more variables are at play when it comes to determining number of queues that can be supported by a given setup. Message throughput, size and resources available. We should let operators determine the load for their individual systems rather than enforcing a static value on all use cases.
	- [x] do quorum queues provide the same level of durability as "classic queues" when the cluster only has a single node ? Yes they do
- [x] Should Queue type be configurable ? yes, as a followup to support a broader set of use cases.

**Time Estimate (optional):**
n/a

**Additional context (optional)**
There is relevant discussion in #518

**Comment by kjnilsson** [comment]
> and we also know that 10k quorum queues is too many for a single RabbitMQ cluster (the cost of consensus is too high)

You may want to revisit that conclusion with 3.10. QQs aren't "light-weight" but 10k queues could well be doable.

**Comment by gab-satchi** [comment]
Closing in favor of new issue with tasks

/close
