### ISSUE TITLE
Add `resource.[requests|limits]` to reconciled objects

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/eventing-rabbitmq#703]
**Problem**
Skimming through the `reconciler` codebase/folders, it seems that none of the deployments/pods created have any `resources` specified. This can lead to performance and stability issues, especially not meeting the documented scaling behavior (#408).

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Operators and users.

**Exit Criteria**
Documented scaling limits (benchmarks) are met even when deploying the resources in a constrained (overutilized) cluster.

**Time Estimate (optional):**
Implementation is straightforward (add `requests` and/or `limits`), but finding the right values might take time (in benchmarks).

**Additional context (optional)**
Even without benchmarking, adding sane defaults (at least `requests`) should be done for the various reconciled resources.

cc/ @salaboy @gabo1208

**Comment by gab-satchi** [comment]
cc @gabo1208 if we can get the resource requirements for when the performance tests were run, that could be a good baseline for the limit

**Comment by gabo1208** [comment]
Sure but you mean the ones defined on the files, totals of the cluster or anything else?

**Comment by gab-satchi** [comment]
Just for the ingress/dispatcher pods. The cluster requirements can be customized by users already but we'd need sane values for the ingress and dispatcher pods

**Comment by gabo1208** [comment]
For setting the limits current limits in the Dispatcher, Adapter:
`Resources: corev1.ResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("300m"),
				corev1.ResourceMemory: resource.MustParse("64Mi")},
			Limits: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("4000m"),
				corev1.ResourceMemory: resource.MustParse("600Mi")},},`
and Ingress:
