### ISSUE TITLE
Are you using the RabbitMQ Broker?

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/eventing-rabbitmq#746]
If you are using Knative Eventing RabbitMQ Broker, we would love to know!

# Why?

Tracking usage in OSS is hard, if you leave a comment on this issue we can better understand who our users are and deliver a better experience for YOU!

# How can I help? 

We'd like to give your organization the opportunity to collaborate more closely with contributors (if you want to)
We want to help promote your organization
We want to show off all the awesome stuff our users are doing
How you can help

Submit a comment in this issue to include the following information, which would then also get included in the [ADOPTERS.md]
(https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/ADOPTERS.MD) file and (if applicable) on the Knative homepage:

```
Organization/Company: 
Website: 
Country: 
Contact: (email or Twitter at least one please!)
Usage scenario: e.g. We use Knative Eventing RabbitMQ Broker for XYZ
Status: Development?/Production?
```

**Comment by embano1** [comment]
```
Organization/Company: VMware
Website: http://vmweventbroker.io
Country: USA
Contact: dl-veba@vmware.com
Usage scenario: We use Knative Eventing RabbitMQ Broker as the backend for the appliance to build event-driven integrations
Status: Development (VEBA is a community-supported VMware Fling)
```
