### ISSUE TITLE
[bug] Crashing ingress and dispatcher pods when connections are disrupted in a 3 node cluster

### ISSUE THREAD

**Issue by gab-satchi** [knative-sandbox/eventing-rabbitmq#764]
I was performing some chaos engineering exercises after having reliability issues with the broker. 

Of course could be a configuration missing (replicated queues?) on the cluster side however 1.4.0 does not seem to recover if a 3 node rabbitmq cluster is being rescheduled (maintainence or autoscaling + PodDistruptionBudget). 

Dispatcher seem to crash and the broker-ingress never reconnects. The situation is only resolved by restarting the broker at which point a successful retry logic is initiated within the broker.

In the meantime I have a custom operator that scrapes the logs of dispatchers and brokers and restarts them when appropriate.

Just wondered if this was of interest.

_Originally posted by @andrewwebber in https://github.com/knative-sandbox/eventing-rabbitmq/issues/760#issuecomment-1126372585_

**Comment by gabo1208** [comment]
Kk! 🤔 Definitely a scenario we haven't tried so I'll be taking a look next week, thanks @andrewwebber :)!
