### ISSUE TITLE
Add Rabbitmq Source docs to Knative docs

### ISSUE THREAD

**Issue by gab-satchi** [knative-sandbox/eventing-rabbitmq#859]
Currently, RabbitmqSource docs are only tracked in this repo. We should include some docs under Knative [docs](https://knative.dev/docs/eventing/sources/) to get started with RabbitmqSource.

**Comment by gabo1208** [comment]
In progress in this PR https://github.com/knative/docs/pull/5137

**Comment by gabo1208** [comment]
Merged docs PR, closing
