### ISSUE TITLE
RabbitmqSource documentation bugs

### ISSUE THREAD

**Issue by gunpuz** [knative-sandbox/eventing-rabbitmq#900]
**Describe the bug**

Documentation is not clear how to configure Rabbitmq Source. 
Its incorrect and inconsistent in different places in the repo

 **Expected behavior**

There should be at least  **1 working** example how to configure rabbitmq source with advanced options

 **To Reproduce**

### Example 1:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/docs/source/source-example.yaml
```
apiVersion: sources.eventing.knative.dev/v1alpha1
```

https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/docs/source#installation
```
apiVersion: sources.knative.dev/v1alpha1
```

### Example 2:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/docs/source/source-example.yaml
```
sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
```

https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/docs/source#installation

```
sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: source-demo
```

### Example 3:

https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/docs/source#creating-and-managing-sources
Typo:
```
delivery.etry
```

### Example 4:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/docs/source/source-example.yaml

How can you configure correctly backOffDelay?
```
backoffDelay: "50ms"
```

```
{"level":"info","ts":"2022-08-19T13:24:15.244Z","caller":"adapter/adapter.go:120","msg":"Initializing Channel with Config: ","Parallelism":1}
{"level":"error","ts":"2022-08-19T13:24:15.246Z","caller":"adapter/adapter.go:202","msg":"error retrieving retryConfig from deliverySpec","error":"failed to parse Spec.BackoffDelay: expected 'P' period mark at the start: 0s","stacktrace":"knative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).PollForMessages\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:202\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:160\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).Start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:134\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext\n\tknative.dev/eventing@v0.33.0/pkg/adapter/v2/main_message.go:118\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapter\n\tknative.dev/eventing@v0.33.0/pkg/adapter/v2/main_message.go:45\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}
{"level":"info","ts":"2022-08-19T13:24:15.248Z","caller":"adapter/adapter.go:211","msg":"Starting GoRoutines Workers: ","WorkerCount":1}
```

 **Knative release version**

v1.6.0

 **Additional context**

It would be awesome if there would be full example with retry configuration how to configure RabbitmqSource.
This is very much needed

**Comment by gabo1208** [comment]
Excellent catches! Thanks for taking the time on filling the issue @gunpuz. I'll be working on these next week :)
/assign

**Comment by gabo1208** [comment]
Thanks for this @gunpuz ! There was indeed a bug when parsing backoff delay in the Source, everything fixed and added a sample on how this works on the sample directory :)!

**Comment by gunpuz** [comment]
That is awesome. Thanks @gabo1208 ! 👍
