### ISSUE TITLE
Release docs: release info incorrect

### ISSUE THREAD

**Issue by gunpuz** [knative-sandbox/eventing-rabbitmq#972]
**Describe the bug**

Release docs are not correct. Release description is the same for 1.8.1 and 1.8.0

Ref: https://github.com/knative-sandbox/eventing-rabbitmq/releases

1.8.0
<img width="851" alt="image" src="https://user-images.githubusercontent.com/39419120/198069994-c3981555-49e3-42f0-a8af-599662261cab.png">
1.8.1
<img width="847" alt="image" src="https://user-images.githubusercontent.com/39419120/198070102-e4b347c1-95ab-4628-a228-69244a7eea8f.png">

 **Expected behavior**

There should be some mention of PR #961 which is probably the same as #959 from issue: #939
<img width="648" alt="image" src="https://user-images.githubusercontent.com/39419120/198070573-8085017d-4fd0-412b-930b-07cb7140330e.png">

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by gabo1208** [comment]
True, we'll try to look at that and see if there is any issue with the release docs action, thank you very much @gunpuz 👍🏼

**Comment by gunpuz** [comment]
Update:

Seems that this is not single-time issue, but it can be reproduced. Newest release contains same info as the previous 2:
![image](https://user-images.githubusercontent.com/39419120/205265589-578d5fbb-3c99-4860-b268-f48dda2a6699.png)

**Comment by gunpuz** [comment]
Update: still there are some issues 
https://github.com/knative-sandbox/eventing-rabbitmq/releases
![image](https://user-images.githubusercontent.com/39419120/229042889-44ed0043-5e23-4880-a759-708396c1c935.png)
![image](https://user-images.githubusercontent.com/39419120/229042970-566952f2-a92e-4b58-b64d-d5bb2cea2386.png)
